cosmetic changes

diff --git a/i40e-lldp-agent.init b/i40e-lldp-agent.init
--- a/i40e-lldp-agent.init
+++ b/i40e-lldp-agent.init
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# x710-lldp-agent Manage x710 lldp agent
+# i40e-lldp-agent Manage x710 lldp agent
 #
 # chkconfig:   - 20 80
 # description: Enables or disabled the lldp agent on x710 intel converged \
-#              network adaptors
+    #              network adaptors
 
 ### BEGIN INIT INFO
 # Provides: 
@@ -22,24 +22,25 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
+SCRIPT=i40e-lldp-agent
 
 _lldp_switch(){
 
-    if [ ! -d /sys/module/i40e ] ; then
-        echo -n "i40e driver not loaded: "
+    if [ ! -d /sys/module/i40e  ] ; then
+        echo -n "${SCRIPT}: i40e driver not loaded. "
         success
         exit 0
     fi
 
     action=$1
     if [[ ! "$action" =~ ^(start|stop)$  ]]; then
-        (echo ""Invalid action \"$action\""" ; exit 2)
+        (echo "${SCRIPT}: Invalid action \"$action\"" ; exit 2)
     fi
 
-    echo $"${action} disabling embedded lldp in x710"
+    echo "${SCRIPT}: ${action} disabling embedded lldp in x710"
     do_unmount=false
     if ! grep -q ' /sys/kernel/debug ' /etc/mtab ; then
-        echo -n "Mount /sys/kernel/debug: "
+        echo -n "${SCRIPT}: Mount /sys/kernel/debug. "
         mount -t debugfs none /sys/kernel/debug  && success || failure
         echo
         do_unmount=true
@@ -47,13 +48,15 @@ _lldp_switch(){
 
     for IFACE_DEBUG_PATH in /sys/kernel/debug/i40e/* 
     do
-        echo "$action on $(cat ${IFACE_DEBUG_PATH}/command)"
+        echo -n "${SCRIPT}: $action on $(cat ${IFACE_DEBUG_PATH}/command)"
         echo lldp $action > ${IFACE_DEBUG_PATH}/command
+        success
+        echo
     done
 
     if $do_unmount; then
         if grep -q ' /sys/kernel/debug ' /etc/mtab ; then 
-            echo -n "Unmount /sys/kernel/debug: "
+            echo -n "${SCRIPT}: Unmount /sys/kernel/debug. "
             umount /sys/kernel/debug && success || failure
             echo
         fi
@@ -105,7 +108,7 @@ case "$1" in
         ;;
     status)
         # TODO: need to work out how to see if x710 lldp agent is turned on 
-        echo 'Who knows'
+        echo "${SCRIPT}: who knows what the status is?"
         #rh_status
         exit 0
         ;;
